theme: jekyll-theme-minimal
title: Introduction to Bioinformatics (BIMM143)
description: Nicholas's Bioinformatics Class (BIMM143, W23)
logo: https://bioboot.github.io/bimm143_S18/assets/img/logo.png
